site_name: Seq-flow Platform
theme:
    name: material
    custom_dir: overrides
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: custom
          #primary: teal
          #accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          primary: custom
          #primary: teal
          #accent: yellow
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.sections
        - navigation.tabs
        - navigation.footer
        - navigation.instant
        - navigation.top
        - announce.dismiss
        - content.code.annotate
        - content.tabs.link
        - content.action.edit
        - header.autohide
extra_css:
    - stylesheets/extra.css
extra:
    generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
        alternate_style: true 
        slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
                case: lower
  - attr_list
  - toc:
        permalink: "¶"
  - footnotes
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
repo_url: https://github.com/voineagulabunsw/gwp
repo_name: voineagulabunsw/gwp
edit_uri: ./edit/main/docs
plugins:
    - search
    - glightbox
    - git-revision-date-localized
nav:
    - 'index.md'
    - 'Getting Started':
        - 'getting_started/first_steps.md'
        - 'getting_started/choosing_interface.md'
    - 'Guides':
        - 'guides/managing_resources.md'
        - 'guides/nf_core_rnaseq.md'
    - 'support.md'