site_name: Genomics Workflow Platform Documentation
theme:
    name: material
    # custom_dir: overrides
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: teal
          #accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          primary: teal
          #accent: yellow
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.footer
        - navigation.instant
        #- navigation.expand
        - navigation.top
        - announce.dismiss
        - content.code.annotate
        - content.tabs.link
        - content.action.edit
#extra_css:
#    - stylesheets/extra.css
extra:
    generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
        alternate_style: true 
  - attr_list
  - toc:
        permalink: "¶"
  - footnotes
  - def_list
repo_url: https://github.com/voineagulabunsw/gwp
repo_name: voineagulabunsw/gwp
edit_uri: ./edit/main
plugins:
    - search
    - glightbox
    - markdownextradata: {}
    - git-revision-date-localized

extra:
    base_url: "https://localhost"
    generator: false

nav:
    - index.md
    - tool_overview.md
    - Guides:
        - Guides/katana.md
        - Guides/nextflow.md
        - RNA-Seq:
            - Guides/RNA-Seq/experimental_design.md
            - Guides/RNA-Seq/bulk.md
            - Guides/RNA-Seq/single_cell.md
            - Guides/RNA-Seq/circular.md

    - support.md