site_name: UNSW Workflow Platform
theme:
    name: material
    # custom_dir: overrides
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: teal
          #accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          primary: teal
          #accent: yellow
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.footer
        - navigation.instant
        - navigation.top
        - announce.dismiss
        - content.code.annotate
        - content.tabs.link
        - content.action.edit
extra:
    generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
        alternate_style: true 
  - attr_list
  - toc:
        permalink: "¶"
  - footnotes
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
repo_url: https://github.com/voineagulabunsw/gwp
repo_name: voineagulabunsw/gwp
edit_uri: ./edit/main/docs
plugins:
    - search
    - glightbox
    - git-revision-date-localized
nav:
    - 'index.md'
    - 'getting_started.md'
    - 'Guides':
        - 'Guides/nextflow.md'
        - 'RNA-Seq':
            - 'Guides/RNA-Seq/experimental_design.md'
            - 'Guides/RNA-Seq/bulk.md'
            - 'Guides/RNA-Seq/single_cell.md'
            - 'Guides/RNA-Seq/circular.md'
    - 'support.md'